name = "pickaxe-tycoon-quven"
compatibility_date = "2024-09-23"
pages_build_output_dir = "out"
account_id = "a17c720d27e1e3b502bef6b0d57c5472"

[vars]
NEXT_PUBLIC_SITE_URL = "https://pickaxe-tycoon.gg"
